/// Flutter icons QuikConnect
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QuikConnect
///      fonts:
///       - asset: fonts/QuikConnect.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QuikConnect {
  QuikConnect._();

  static const _kFontFam = 'QuikConnect';

  static const IconData qrcode = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qrcode_scan = const IconData(0xe801, fontFamily: _kFontFam);
}
